config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments,  only: [:new, :create, :destroy]
      resources :likes,  only: [:create] 
    end
  end
  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_create :increment_post_comments_counter

  private

  def increment_post_comments_counter
    post.increment!(:comments_counter)
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments

    if @comments
      render json: { status: 'Success', message: 'Comment fetched successfully', data: @comments }, status: :ok
    else
      render json: { status: 'Error', message: 'No comments found!', data: @comments.errors },
             status: :bad_request
    end
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comments = @post.comments.new(comment_params)
    @comments.post_id = @post.id
    @comments.author_id = @user.id

    if @comments.save
      render json: { status: 'Success', message: 'Comment Created', data: @comments }, status: :ok
    else
      render json: { status: 'Not Found', message: 'Details not found', data: @comments.errors },
             status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @user = current_user
    @comment = @user.comments.build(comment_params)
    @comment.post_id = params[:post_id]

    if @comment.save
      flash[:success] = 'Comment created successfully'
    else
      flash[:error] = 'Something went wrong.'
      puts @comment.errors.full_messages
      render :new
    end

    redirect_to user_post_path(params[:user_id], @comment.post_id)
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment # Authorize the action
    @post = @comment.post
    @post.decrement!(:comments_counter)
    @comment.destroy
    redirect_to user_post_path(params[:user_id], @comment.post_id), notice: 'Comment was successfully destroyed.'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/views/comments/new.html.erb
<section class="container mt-5">
  <div class="row justify-content-center align-items-center "> <!-- Center vertically using Flexbox -->
    <div class="col-6 border border-dark rounded-1  border-2 p-5">
    <h1 class="text-center">Add A Comment</h1>
        <% if flash[:error].present? %>
            <div class="alert alert-danger">
            <%= flash[:error] %>
            </div>
        <% end %>
      
      <%= form_with(model: @comment, url: user_post_comments_path(@user, @post)) do |form| %>

        <div class="form-group">
            <%= form.label :body, 'Comment' %>
            <%= form.text_area :body, class: 'form-control' %>
        </div>

        <div class="form-group mt-2">
          <%= form.submit 'Create Post', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</section>