config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments,  only: [:new, :create, :destroy]
      resources :likes,  only: [:create] 
    end
  end
  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  attribute :posts_counter, :integer, default: 0

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    users = User.all

    if users
      render json: { status: 'Success!', message: 'All the Users fetched successfully', data: users }, status: :ok
    else
      render json: { status: 'Error!', message: 'Something went wrong! Failed to fetch users', errors: users.errors },
             status: :bad_request
    end
  end

  def show
    user = User.find_by(id: params[:id])

    if user

      render json: { status: 'Success', message: 'User fetched successfully', data: user }, status: :ok
    else

      render json: { status: 'Error', message: 'Failed to fetch user', errors: user.errors }, status: :bad_request
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/views/users/index.html.erb
<section id="body-content" class="container">  
   <%= render partial: 'shared/signout' %>
    
    <%= link_to "Create New Post", new_user_post_path(current_user.id), class: "btn btn-primary" %>
    
    <% @users.each do |user| %>
        <div class="row mt-4">
            <div class="col-lg-2">
                <%# <%= image_tag("default.jpg", alt: "Default", style: "width: 70%;") %> 
                <img id="user-image" src="<%= user.photo %>" alt="User Photo" style="width: 70%;">

            </div>
            <div class="col-lg-10 border border-dark d-flex align-items-center">
                <div class="user-lists w-100">
                    <h2 class="text-dark"><%= link_to user.name, user_path(user) %></h2>
                    <p class="d-flex justify-content-end">Number Of posts <%= user.posts_counter %></p>
                </div>
            </div>
        </div>
    <% end %>

</section>

app/views/users/show.html.erb
<section id="body-content" class="container">
    <%= render partial: 'shared/user', locals: { user: @user } %>
    <div class="row mt-4">
        <div class="col-lg-12 border border-dark">
            <h4>Bio</h4>
            <p class="mt-2"><%= @user.bio %></p>
        </div>
    </div>

    <% @posts.each_with_index do |post, index| %>  
        <div class="row mt-4">
            <div class="col-lg-12 border border-dark">
                <h4 class="pt-2"><%= link_to "Post ##{index + 1}", user_post_path(@user, post), class: "text-dark" %></h4>
                <p class="mt-2"><%= truncate(post.text, length: 200, omission: '...') %></p>

                <p class="d-flex justify-content-end">
                   <%= render partial: 'shared/like', locals: { user: @user, post: post } %>
                </p>
                <p class="d-flex justify-content-end"><%= link_to "Add Comment", new_user_post_comment_path(@user, post), class:"text-primary" %>,  Comments <%= post.comments_counter %>, Likes <%= post.likes_counter%></p>
            </div>
        </div>
    <% end %>

    <div class="row mt-4 justify-content-center">
        <div class="col-lg-12 text-center">
            <%= link_to "View All Posts", user_posts_path(@user), class: "btn btn-primary" %>
        </div>
    </div>
</section>