config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments,  only: [:new, :create, :destroy]
      resources :likes,  only: [:create] 
    end
  end
  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end


end

app/views/shared/_like.html.erb
<%= form_with(url: user_post_likes_path(@user, post), method: :post) do |form| %>
    <%= form.hidden_field :post_id, value: post.id %>
    <%= form.submit "Like", class: "btn btn-primary" %>
<% end %>

app/views/shared/_signout.html.erb
<% if user_signed_in? %>
        <%= form_tag(destroy_user_session_path, method: :delete, class: "d-flex justify-content-center") do %>
          <%= submit_tag("Sign Out", class: "btn btn-danger") %>
        <% end %>
    <% end %>

app/views/shared/_user.html.erb
<div class="row mt-4">
<%= render partial: 'shared/signout' %>
    <div class="col-lg-2">
        <img id="user-image" src="<%= user.photo %>" alt="User Photo" style="width: 70%;">
    </div>
    <div class="col-lg-10 border border-dark d-flex align-items-center">
        <div class="user-lists w-100">
            <h2 class="text-dark"><%= @user.name %></h2>
            <p class="d-flex justify-content-end">Number Of posts <%= @user.posts_counter %></p>
        </div>
    </div>
</div>