config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments,  only: [:new, :create, :destroy]
      resources :likes,  only: [:create] 
    end
  end
  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes

  attribute :comments_couter, :integer, default: 0
  attribute :likes_counter, :integer, default: 0

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(3)
  end
  after_create :increment_user_posts_counter

  private

  def increment_user_posts_counter
    author.increment!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @posts = Post.includes(:author).where(author_id: params[:user_id])
    @user = User.includes(:posts).find(params[:user_id])

    if @posts
      render json: { status: 'Success', message: 'Posts fetched successfully', data: @posts }, status: :ok
    else
      render json: { status: 'Error', message: 'Failed to fetch posts!', errors: @posts.errors }, status: :bad_request
    end
  end

  def show
    @post = Post.includes(:author).find_by(author_id: params[:user_id], id: params[:id])
    @user = @post.author

    if @post
      render json: { status: 'Success', message: 'Post fetched successfully', data: @post }, status: :ok
    else
      render json: { status: 'Error', message: 'Failed to fetch post!', errors: @post.errors }, status: :bad_request
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(comments: :author)
  end

  def show
    logger.debug(params)
    @user = User.find(params[:user_id])
    @post = @user.posts.includes(:comments).find(params[:id])
    @comments = @post.comments
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_posts_path, notice: 'Post was successfully created.'
    else
      flash.now[:alert] = 'Something Wrong, Cannot create a new post'
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @author = @post.author
    @author.decrement!(:posts_counter)
    @post.destroy
    if @post.destroy
      redirect_to user_posts_path(current_user), notice: 'post was successfully deleted.'
    else
      redirect_to redirect_url, alert: 'Failed to delete the post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :user_id)
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/views/posts/index.html.erb
<section class="container">
    <%= render partial: 'shared/user', locals: { user: @user } %>
    <% @posts.each do |post| %>  
        <div class="row mt-4">
            <div class="col-lg-12 border border-dark">
               <div class="row">
                    <div class="col-lg-10">
                        <h4 class="pt-2"><%= link_to post.title, user_post_path(@user, post), class: "text-dark" %></h4>
                        <p class="mt-2"><%= truncate(post.text, length: 200, omission: '...') %></p>
                        <p class="d-flex justify-content-end"><%= link_to "Add Comment", new_user_post_comment_path(@user, post), class:"text-dark" %>, Comments <%= post.comments_counter %>, Likes <%= post.likes_counter%></p>
                    </div>
                    <div class="col-lg-2">
                        <p class="d-flex justify-content-end">
                           <%= render partial: 'shared/like', locals: { user: @user, post: post } %>
                        </p>
                        <% if post.author.id == current_user.id || current_user.admin? %>
                            <%= button_to 'Delete Post', user_post_path(post.author, post), method: :delete, class: 'btn btn-danger' %>
                        <% end %>
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 border border-dark">
                <table class="table table-border">
                    <tbody>
                        <% post.comments.each do |comment| %>
                            <tr>
                                <td><%= comment.author.name %>: <%= comment.body %></td>
                                <td>
                                    <% if can? :destroy, comment %>
                                        <%= button_to 'Delete', user_post_comment_path(post.author, post, comment), method: :delete, class: 'btn btn-light text-danger btn-sm'%>
                                    <% end %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>

            </div>
        </div>
    <% end %>
    <div class="pagination">pagination</div>
</section>

app/views/posts/new.html.erb
<section class="container mt-5">
<%= render partial: 'shared/signout' %>
  <div class="row justify-content-center align-items-center "> 
    <div class="col-6 border border-dark rounded-1  border-2 p-5">
    <h1 class="text-center">Add new post</h1>
       <% if flash[:alert].present? %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= form_with(model: @post, url: user_posts_path) do |form| %>
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :text %>
          <%= form.text_area :text, class: 'form-control' %>
        </div>
<%= form.hidden_field :author_id, value: current_user.id %>

        <div class="form-group mt-2">
          <%= form.submit 'Create Post', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="container">
 <%= render partial: 'shared/signout' %>
    <div class="row mt-4">
        <div class="col-lg-12 border border-dark">
<div class="row">
                <div class="col-lg-10">
                    <h4 class="pt-2">'<%= @post.title %>' by <%= @user.name %></h4>
                    <p class="mt-2"><%= @post.text %></p>
                    <p class="d-flex justify-content-end"><%= link_to "Add Comment", new_user_post_comment_path(current_user, @post), class:"text-dark" %>, Comments <%= @post.comments_counter %>, Likes <%= @post.likes_counter%></p>    
                </div>
                <div class="col-lg-2">
                     <p class="d-flex justify-content-end">
                        <%= render partial: 'shared/like', locals: { user: @user, post: @post } %>
                    </p>
                    <% if @post.author.id == current_user.id || current_user.admin? %>
                        <%= button_to 'Delete Post', user_post_path(@post.author, @post), method: :delete, class: 'btn btn-danger' %>
                    <% end %>
                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 border border-dark">
            <table class="table table-border">
                <tbody>
                    <% @comments.each do |comment| %>
                        <tr>
                            <td><%= comment.author.name %>: <%= comment.body %></td>
                            <td>
                                <% if can? :destroy, comment %>
                                    <%= button_to 'Delete', user_post_comment_path(@post.author, @post, comment), method: :delete, class: 'btn btn-light text-danger btn-sm'%>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>

        </div>
    </div>
</section>